import { login } from "../controllers/login.js";
import {Router} from 'express';
import { signup } from "../controllers/signup.js";
import { passwordreset, reset, verifypassword } from "../controllers/reset.js";
import { extracturl } from "../controllers/extracturl.js";
import { addproblem } from "../controllers/addproblem.js";
import { protect } from "../controllers/authmiddleware.js";
import { getstrugglingproblem } from "../controllers/getstrugglingproblem.js";
import { getmasteredproblem } from "../controllers/getmasteredproblem.js";
import { markasmastered } from "../controllers/markasmastered.js";
import { markasstruggling } from "../controllers/markasstruggling.js";
import { getprofile } from "../controllers/getprofile.js";
import { deleteproblem } from "../controllers/deleteproblem.js";
export const userRouter=Router();
console.log("Auth router working");
userRouter.route('/signup').post(signup)
userRouter.route('/login').post(login);
userRouter.route('/reset').post(reset);
userRouter.route('/reset/verify').post(verifypassword);
userRouter.route('/reset/passwordreset').post(passwordreset);
userRouter.route('/addproblem/extracturl').post(protect,extracturl);
userRouter.route('/addproblem/addproblem').post(protect,addproblem);
userRouter.route('/getproblem/struggling').get(protect,getstrugglingproblem);
userRouter.route('/getproblem/mastered').get(protect,getmasteredproblem);
// userRouter.route('/markasmastered').patch(protect,markasmastered);
// userRouter.route('/markasstruggling').patch(protect,markasstruggling);
userRouter.route('/markasmastered/:id').patch(protect, markasmastered);
userRouter.route('/markasstruggling/:id').patch(protect, markasstruggling);
userRouter.route('/profile').get(protect,getprofile);
userRouter.route('/deleteproblem/:id').delete(protect, deleteproblem);